provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  kubesec:
    lang: dockerfile
    handler: ./kubesec
    image: alexellis2/kubesec:latest
    annotations:
      com.openfaas.health.http.path: "/healthz"
    labels:
      com.openfaas.scale.zero: false
